- name: Add the user 'skyvue-tomcat' with a bash shell
  user:
    name: skyvue-tomcat
    shell: /bin/bash
    append: yes

- name: Create a directory for the app to live in
  file:
    path: /var/demoapp
    state: directory
    mode: '0777'

- name: Create a directory for out properties to be externalized
  file:
    path: /var/demoapp/config
    state: directory
    mode: '0777'

# Because we manually sent it over to /tmp, this is where we'd usually just pull it from Artifactory
- name: stat /tmp for binary
  stat: path=/tmp/demo-0.0.1-SNAPSHOT.jar
  register: app_binary

- name: Move binary to folder
  command: mv /tmp/demo-0.0.1-SNAPSHOT.jar /var/demoapp/demo-0.0.1-SNAPSHOT.jar
  when: app_binary.stat.exists

- name: Change jar to be available to everyone
  file:
    path: /var/demoapp/demo-0.0.1-SNAPSHOT.jar
    owner: skyvue-tomcat
    group: skyvue-tomcat
    mode: '0777'