---
# Also - https://github.com/remyma/ansible-springboot

- hosts: appserver
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - up_to_date
    - java
    - boot-deploy-setup
    - demo-app-deployment
    